server:
  port: 8501
spring:
  application:
    name: ly-search
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.25.152
    username: lmhitysu
    password: 123456
    virtual-host: lmVirtual
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}