server:
  port: 8701
spring:
  application:
    name: ly-sms-service
  rabbitmq:
    host: 192.168.25.152
    username: lmhitysu
    password: 123456
    virtual-host: lmVirtual
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: ly-user-service
    instance-id: ${spring.application.name}:${server.port}
leyou:
  sms:
    accessKeyId: LTAIQtWBkmZMno91 # 你自己的accessKeyId
    accessKeySecret: ZsnBoU9wJw0pyiJuUPzbDp0c5dKgac # 你自己的AccessKeySecret
    signName: 天才商城 # 签名名称
    TemplateCode: SMS_171540803 # 模板名称
