server:
  port: 8401
spring:
  application:
    name: ly-upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka
  instance:
    hostname: ly-uplod
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5 #每隔５ｓ发送发一次心跳检测
    lease-expiration-duration-in-seconds: 10 # 10s秒不发送就过期
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: 192.168.25.133:22122