server:
  port: 8702
spring:
  application:
    name: ly-auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: ly-auth-service
    instance-id: ${spring.application.name}:${server.port}
ly:
  jwt:
    secret: lmhitysu@l63.com*}~
    pubKeyPath: /home/liming/RsaAugorithm/rsa.pub
    priKeyPath: /home/liming/RsaAugorithm/rsa.pri
    expire: 30
    cookieName: LY_TOKEN
    cookieMaxAge: 30
